# See https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html and
# https://github.com/rook/rook for examples and configuration values
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.5
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: false
  monitoring:
    # requires Prometheus operator CRDs to be pre-installed
    enabled: false
  crashCollector:
    disable: false
  cleanupPolicy:
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
    allowUninstallWithVolumes: false
  resources:
    mgr:
      requests:
        cpu: "100m"
        memory: "500Mi"
    mon:
      requests:
        cpu: "100m"
        memory: "1Gi"
    osd:
      requests:
        cpu: "500m"
        memory: "1Gi"
#    prepareosd:
    crashcollector:
      requests:
        cpu: "1m"
        memory: "15Mi"
#    cleanup:
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    useAllNodes: true
    useAllDevices: true

  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
