name: Bug Report
description: Create a bug report to help us improve Welkin Kubespray
labels: kind/bug
body:
  - type: markdown
    attributes:
      value: |-
        Thank you for taking the time to help improve Welkin!

        > [!warning]
        > **This is a public repository, ensure not to disclose:**
        >
        > - [x] personal data beyond what is necessary for interacting with this issue, nor
        > - [x] business confidential information, such as customer names.
  - type: textarea
    attributes:
      label: Experienced behaviour
      description: Clear and concise description of what you experienced.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Clear and concise description of what you expected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimal example that shows the behaviour you experienced.
      placeholder: |-
        1. Go to '...'
        1. Click on '...'
        1. Scroll down to '...'
        1. See error
    validations:
      required: true
  - type: input
    attributes:
      label: Welkin Kubespray Version
      placeholder: vX.Y.Z-ck8sP
    validations:
      required: true
  - type: input
    attributes:
      label: Welkin Apps Version
      placeholder: vX.Y.Z
    validations:
      required: false
  - type: input
    attributes:
      label: Kubernetes Version
      placeholder: vX.Y.Z
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |-
        Any additional information about the bug here.

        Include screenshots if applicable.
    validations:
      required: false
