name: Feature Request
description: Create a feature request to help us improve Welkin Kubespray
labels: kind/feature
body:
  - type: markdown
    attributes:
      value: |-
        Thank you for taking the time to help improve Welkin!

        > [!warning]
        > **This is a public repository, ensure not to disclose:**
        >
        > - [x] personal data beyond what is necessary for interacting with this issue, nor
        > - [x] business confidential information, such as customer names.
  - type: textarea
    attributes:
      label: Proposed feature
      description: The what and the why
      placeholder: |-
        Clear and concise description of the feature you would like and the problem it will solve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed alternatives
      description: The how
      placeholder: |-
        Clear and concise description of the alternatives you have considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |-
        Any additional information about the feature request here.

        Include screenshots if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Definition of done
      description: Testable conditions for when this feature can be considered completed
      placeholder: |-
        - [ ] Conditions...
      value: |-
        - [ ] Conditions...
        - [ ] This new feature is covered by public documentation
    validations:
      required: true
