name: General Issue
description: Create a general issue to help us improve Welkin Kubespray
body:
  - type: markdown
    attributes:
      value: |-
        Thank you for taking the time to help improve Welkin!

        > [!warning]
        > **This is a public repository, ensure not to disclose:**
        >
        > - [x] personal data beyond what is necessary for interacting with this issue, nor
        > - [x] business confidential information, such as customer names.
  - type: textarea
    attributes:
      label: Description
      description: The what and the why
      placeholder: |-
        Clear and concise description of the goal for this issue and why it is needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |-
        Any additional information about the general issue here.

        Include screenshots if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Definition of done
      description: Testable conditions for when this can be considered completed
      placeholder: |-
        - [ ] Conditions...
    validations:
      required: true
