kube_oidc_auth: true
kube_oidc_url: <IDP-URL|https://dex.BASE-DOMAIN>
kube_oidc_client_id: <id-from-IDP|kubelogin>
kube_oidc_client_secret: <secret-from-IDP|secret-from-dex>
kube_oidc_username_claim: "email"
kubeconfig_cluster_name: <CHANGE-ME-ENVIRONMENT-NAME-sc|CHANGE-ME-ENVIRONMENT-NAME-wc>
## don't add "groups" when connecting directly to google
# kube_oidc_groups_claim: "groups"
kube_oidc_extra_scopes: []
kube_oidc_apiserver_endpoint: <Public-IP/DNS-to-apiserver-or-loadbalancer>
kube_oidc_apiserver_port: "6443"
kubeconfig_file_name: <kube_config_sc.yaml|kube_config_wc.yaml>
artifacts_dir: "{{ inventory_dir }}/../.state"
create_oidc_kubeconfig: true
cluster_admin_users:
- test@example.com
cluster_admin_groups:
- admin-group
kubeconfig_localhost: false

kube_apiserver_enable_admission_plugins:
  - "PodSecurityPolicy"
  - "NamespaceLifecycle"
  - "LimitRanger"
  - "ServiceAccount"
  - "DefaultStorageClass"
  - "DefaultTolerationSeconds"
  - "MutatingAdmissionWebhook"
  - "ValidatingAdmissionWebhook"
  - "ResourceQuota"
  - "NodeRestriction"

kube_kubeadm_apiserver_extra_args:
  delete-collection-workers: "3"

kube_proxy_mode: iptables
kube_proxy_metrics_bind_address: "0.0.0.0:10249"

container_manager: containerd

enable_nodelocaldns: false

kubernetes_audit: true
audit_log_path: "/var/log/audit/kube-apiserver-audit.log"
audit_log_maxage: 7

audit_policy_custom_rules: |-
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      # Resource "pods" doesn't match requests to any subresource of pods,
      # which is consistent with the RBAC policy.
      resources: ["pods"]
  # Log "pods/log", "pods/status" at Metadata level
  - level: Metadata
    resources:
    - group: ""
      resources: ["pods/log", "pods/status"]

  # Don't log requests to a configmap called "controller-leader"
  - level: None
    resources:
    - group: ""
      resources: ["configmaps"]
      resourceNames: ["controller-leader"]

  # Don't log watch requests by the "system:kube-proxy" on endpoints or serv
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
    - group: "" # core API group
      resources: ["endpoints", "services"]

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
    - "/api*" # Wildcard matching.
    - "/version"

  # Log the request body of configmap changes in kube-system.
  - level: Request
    resources:
    - group: "" # core API group
      resources: ["configmaps"]
    # This rule only applies to resources in the "kube-system" namespace.
    # The empty string "" can be used to select non-namespaced resources.
    namespaces: ["kube-system"]

  # Log configmap and secret changes in all other namespaces at the Metadata
  - level: Metadata
    resources:
    - group: "" # core API group
      resources: ["secrets", "configmaps"]

  # Log all other resources in core and extensions at the Request level.
  - level: Request
    resources:
    - group: "" # core API group
    - group: "extensions" # Version of group should NOT be included.

  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"
podsecuritypolicy_enabled: true
calico_felix_prometheusmetricsenabled: true

kubelet_config_extra_args:
  imageGCHighThresholdPercent: 75
  imageGCLowThresholdPercent: 70

calico_ipip_mode: 'Always'
calico_vxlan_mode: 'Never'
calico_network_backend: 'bird'

kube_profiling: false

kube_scheduler_bind_address: 127.0.0.1
kube_kubeadm_scheduler_extra_args:
    profiling: false

kube_controller_manager_bind_address: 127.0.0.1

kubelet_secure_addresses: >-
  {%- for host in groups['kube_control_plane'] -%}
    {{ hostvars[host]['ip'] | default(fallback_ips[host]) }}{{ ' ' if not loop.last else '' }}
  {%- endfor -%}
