# preset: ceph-4750

cephClusterSpec:
  resources:
    crashcollector:
      requests:
        cpu: 1m
        memory: 15Mi
      limits:
        cpu: 50m
        memory: 60Mi
    logcollector:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 1Gi
    mgr:
      requests:
        cpu: 50m
        memory: 2Gi
      limits:
        cpu: 200m
        memory: 3Gi
    mgr-sidecar:
      requests:
        cpu: 100m
        memory: 40Mi
      limits:
        cpu: 500m
        memory: 100Mi
    mon:
      requests:
        cpu: 50m
        memory: 2Gi
      limits:
        cpu: 200m
        memory: 3Gi
    osd:
      requests:
        cpu: 200m
        memory: 5Gi
      limits:
        cpu: 400m
        memory: 6Gi
    prepareosd:
      requests:
        cpu: 500m
        memory: 50Mi
    exporter:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        cpu: 50m
        memory: 50Mi
    cleanup:
      requests:
        cpu: 500m
        memory: 50Mi
