{{- $configPath := requiredEnv "CK8S_CONFIG_PATH" }}

missingFileHandler: Error

helmDefaults:
  createNamespace: false
  skipDeps: true
  timeout: 600

environments:
  {{- $values := printf "%s/rook/values.yaml" $configPath | readFile | fromYaml }}
  {{- range $cluster, $value := $values.clusters }}
  {{ $cluster }}:
    values:
      - {{ $values.commons | toYaml | nindent 8 | trim }}
      - {{ $value | toYaml | nindent 8 | trim }}
  {{- end }}

---

releases:
  - name: rook-ceph-namespace
    namespace: kube-system
    labels:
      app: namespace
      stage: bootstrap
    chart: ./charts/namespaces
    version: 0.1.0
    values:
      - values/namespace.yaml.gotmpl

  - name: rook-ceph-networkpolicies
    namespace: rook-ceph
    labels:
      app: netpol
    installed: {{ .Values.networkPolicies.enabled }}
    chart: ./charts/networkpolicies
    version: 0.1.0
    needs:
      - kube-system/rook-ceph-namespace
    values:
      - values/networkpolicies.yaml.gotmpl

  - name: rook-ceph-podsecuritypolicies
    namespace: rook-ceph
    labels:
      app: psp
    installed: {{ .Values.podSecurityPolicies.enabled }}
    chart: ./charts/podsecuritypolicies
    version: 0.1.0
    needs:
      - kube-system/rook-ceph-namespace
    values:
      - values/podsecuritypolicies.yaml.gotmpl

  - name: rook-ceph
    namespace: rook-ceph
    labels:
      app: operator
      stage: bootstrap
    chart: ./upstream/rook-ceph
    version: v1.14.4
    disableValidationOnInstall: true
    needs:
      - kube-system/rook-ceph-namespace
    values:
      - values/operator.yaml.gotmpl

  - name: rook-ceph-cluster
    namespace: rook-ceph
    labels:
      app: cluster
      stage: bootstrap
    chart: ./upstream/rook-ceph-cluster
    version: v1.14.4
    disableValidationOnInstall: true
    needs:
      - kube-system/rook-ceph-namespace
      - rook-ceph/rook-ceph
    values:
      - values/cluster-presets/{{ .Values.cluster.preset }}.yaml
      - values/cluster.yaml.gotmpl

  - name: rook-ceph-dashboards
    namespace: monitoring
    labels:
      app: dashboards
    installed: {{ .Values | get "monitoring.installGrafanaDashboards" false }}
    chart: ./charts/rook-ceph-dashboards
    version: 0.1.0

  - name: rook-ceph-rules
    namespace: monitoring
    labels:
      app: rules
    installed: {{ .Values | get "monitoring.installPrometheusRules" false }}
    chart: ./charts/rook-ceph-rules
    version: 0.1.0

  - name: rook-ceph-toolbox
    namespace: rook-ceph
    labels:
      app: toolbox
      stage: bootstrap
    installed: {{ .Values.cluster | get "toolbox.enabled" true }}
    chart: ./charts/rook-ceph-toolbox
    version: 0.1.0
    needs:
      - kube-system/rook-ceph-namespace
      - rook-ceph/rook-ceph
      - rook-ceph/rook-ceph-cluster
    values:
      - values/toolbox.yaml.gotmpl
