etcd_kubeadm_enabled: true

cloud_provider: "external"
external_cloud_provider: "vsphere"

# For details, see https://github.com/kubernetes-sigs/kubespray/blob/master/docs/vsphere.md#out-of-tree-vsphere-cloud-provider
external_vsphere_vcenter_ip: ""
external_vsphere_insecure: "false"

# TODO change to using environment variables when https://github.com/kubernetes-sigs/kubespray/pull/7646 is merged and in a release
external_vsphere_user: ""
# external_vsphere_password: "" # Set via `ansible-playbook ... --extra-vars "external_vsphere_password=${VSPHERE_PASSWORD}"`

external_vsphere_datacenter: ""
external_vsphere_kubernetes_cluster_id: ""
vsphere_csi_enabled: true
