- hosts: k8s_cluster
  roles:
  - role: kubespray-defaults
    when:
    - create_oidc_kubeconfig
    - inventory_hostname == groups['kube_control_plane'][0]
  tasks:
  - name: Add cluster admin rbac
    when:
    - create_oidc_kubeconfig
    - inventory_hostname == groups['kube_control_plane'][0]
    block:
    - name: Render templates for cluster admin ClusterRoleBinding
      template:
        src: "cluster_admin_crb.yml.j2"
        dest: "{{ kube_config_dir }}/cluster_admin_crb.yml"
      register: cluster_admin_manifests

    - name: Add ClusterRoleBinding for cluster admin
      kube:
        name: "oidc-cluster-admin2"
        kubectl: "{{ bin_dir }}/kubectl"
        filename: "{{ kube_config_dir }}/cluster_admin_crb.yml"
        state: "latest"
      register: result
      until: result is succeeded
      retries: 10
      delay: 6
