- name: Install systemd timer to kill stuck apt processes
  hosts: all
  become: true

  tasks:
    - name: Copy kill_stuck_apt.sh to /usr/local/bin
      copy:
        dest: /usr/local/bin/kill_stuck_apt.sh
        content: |
          #!/bin/bash

          # Find and kill apt-related processes that have been running for more than 24 hours (86400 seconds)
          PIDS=$(ps -eo pid,etimes,comm | awk '
            $3 ~ /^apt(-get|itude)?$/ && $2 > 86400 {
              print $1
            }
          ')

          for pid in $PIDS; do
            echo "Killing stuck apt process PID=$pid"
            kill -9 "$pid"
          done
        mode: '0755'

    - name: Deploy systemd service unit
      template:
        src: templates/kill-stuck-apt.service.j2
        dest: /etc/systemd/system/kill-stuck-apt.service
        mode: '0644'

    - name: Deploy systemd timer unit
      template:
        src: templates/kill-stuck-apt.timer.j2
        dest: /etc/systemd/system/kill-stuck-apt.timer
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start systemd timer
      systemd:
        name: kill-stuck-apt.timer
        enabled: true
        state: started
