- hosts: k8s_cluster[0]
  tasks:
  - name: check param
    fail:
      msg: Cannot have both kubeconfig_localhost and create_oidc_kubeconfig set.
    when:
    - kubeconfig_localhost | default(false)
    - create_oidc_kubeconfig | default(false)

- hosts: k8s_cluster
  roles:
  - role: kubespray-defaults
    when:
    - create_oidc_kubeconfig
    - inventory_hostname == groups['kube_control_plane'][0]
  tasks:
  - name: Create OIDC kubeconfig
    when:
    - create_oidc_kubeconfig
    - inventory_hostname == groups['kube_control_plane'][0]
    block:
    - name: Get kubeconfig CA
      shell: "cat {{ kube_cert_dir }}/ca.crt | base64 --wrap 0"
      args:
        executable: /bin/bash
      register: ca_cert

    - name: Render templates for OIDC kubeconfig
      template:
        src: "kube_config_oidc.yml.j2"
        dest: "{{ kube_config_dir }}/{{ kubeconfig_file_name }}"
      register: oidc_kubeconfig

    - name: Copy OIDC kubeconfig to ansible host
      fetch:
        src: "{{ kube_config_dir }}/{{ kubeconfig_file_name }}"
        dest: "{{ artifacts_dir }}/"
        flat: yes
        validate_checksum: no
      become: no
      run_once: yes

  - name: Move cluster admin kubeconfig
    command: mv "{{ artifacts_dir }}/admin.conf" "{{ artifacts_dir }}/{{ kubeconfig_file_name }}"
    delegate_to: localhost
    become: no
    run_once: yes
    args:
      removes: "{{ artifacts_dir }}/admin.conf"
    when:
    - kubeconfig_localhost
