- name: Patch kube-proxy image
  hosts: "{{ groups['kube_control_plane'] | first }}"
  tasks:
    - name: Patch kube-proxy DaemonSet with pinned image
      shell: >-
        kubectl --kubeconfig /etc/kubernetes/admin.conf -n kube-system set image daemonset/kube-proxy kube-proxy={{ kube_proxy_image }}
      args:
        executable: /bin/bash
      run_once: true
