kubeadm_patches:
  - target: kube-apiserver
    type: strategic
    patch:
      spec:
        containers:
        - name: kube-apiserver
          image: registry.k8s.io/kube-apiserver:v1.35.4@sha256:06b4bb208634a107ab9e6c50cdb9df178d05166a700c0cc448d59522091074b5

  - target: kube-controller-manager
    type: strategic
    patch:
      spec:
        containers:
        - name: kube-controller-manager
          image: registry.k8s.io/kube-controller-manager:v1.35.4@sha256:7b036c805d57f203e9efaf43672cff6019b9083a9c0eb107ea8500eace29d8fd

  - target: kube-scheduler
    type: strategic
    patch:
      spec:
        containers:
        - name: kube-scheduler
          image: registry.k8s.io/kube-scheduler:v1.35.4@sha256:9054fecb4fa04cc63aec47b0913c8deb3487d414190cd15211f864cfe0d0b4d6

  - target: etcd
    type: strategic
    patch:
      spec:
        containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.6.10@sha256:6742378fabf521b47edd637914d508061528924d5915af0fd5d6379cfef89b7a
