name: pre-commit

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
