name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - release-[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.PRIVATE_SIGNING_AUTH_KEY }}
          submodules: recursive

      - name: Import GPG key
        env:
          PRIVATE_SIGNING_KEY: ${{ secrets.PRIVATE_SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ vars.SIGNING_KEY_ID }}
          SIGNING_KEY_NAME: ${{ vars.SIGNING_KEY_NAME }}
          SIGNING_KEY_EMAIL: ${{ vars.SIGNING_KEY_EMAIL }}
        run: |
          gpg --import <(echo "${PRIVATE_SIGNING_KEY}")

          git config --global user.signingkey "${SIGNING_KEY_ID}"
          git config --global user.name "${SIGNING_KEY_NAME}"
          git config --global user.email "${SIGNING_KEY_EMAIL}"

      - name: Get series
        id: get_series
        run: echo "SERIES=$(echo "${{ github.ref_name }}" | sed 's/release-\(.*\.[0-9]*\)$/\1/')" >> "${GITHUB_OUTPUT}"

      - name: Create signed commit and tag
        id: create_tag
        run: |
          TAG_NAME="v$(echo "${{ github.head_ref }}" | sed 's/staging-\(.*\)$/\1/')"

          git commit -S --allow-empty -m "Release ${TAG_NAME}"
          git tag -s "${TAG_NAME}" -m "Release ${TAG_NAME}"

          git push --atomic origin "${{ github.ref_name}}" "${TAG_NAME}"
          echo "TAG_NAME=${TAG_NAME}" >> "${GITHUB_OUTPUT}"

      - name: Create Signed Archive
        id: create_archive
        run: |
          ARCHIVE_NAME="${GITHUB_REPOSITORY##*/}-${{ steps.create_tag.outputs.TAG_NAME }}"
          TEMP_DIR=$(mktemp -d)
          # export variables to be able to access them within `git submodule foreach`
          export ARCHIVE_NAME
          export TEMP_DIR

          # zip archive
          # -----------
          # since zip does not support concatenating multiple zips, we use git archive and pipe it to tar to extract
          # the main repo and its submodules to a temporary directory, while respecting .gitattributes and keeping
          # the same folder structure
          git archive --format=tar HEAD | tar -x -C "${TEMP_DIR}"
          git submodule foreach --recursive '
              # `displaypath` is a `submodule foreach` command for the relative path from the CWD to the root directory
              mkdir -p "${TEMP_DIR}/${displaypath}"
              git archive --format=tar HEAD | tar -x -C "${TEMP_DIR}/${displaypath}"
          '
          pushd "${TEMP_DIR}"
          # zip main repo and any submodules into one
          zip -r "${GITHUB_WORKSPACE}/${ARCHIVE_NAME}.zip" .
          popd
          rm -rf "${TEMP_DIR}"

          # tar archive
          # -----------
          # create tar of the main repo which will not include any submodules
          git archive --format=tar --output="${GITHUB_WORKSPACE}/${ARCHIVE_NAME}.tar" HEAD
          git submodule foreach --recursive '
              # create tar of submodule with prefix of the submodule name to preserve folder structure
              git archive --format=tar --prefix="${displaypath}/" --output="${displaypath}.tar" HEAD
              # merge submodule tar with the main repo tar
              tar --concatenate --file="${GITHUB_WORKSPACE}/${ARCHIVE_NAME}.tar" "${displaypath}.tar"
              rm "${displaypath}.tar"
          '
          gzip --best --verbose "${GITHUB_WORKSPACE}/${ARCHIVE_NAME}.tar"
          gpg --batch --yes --output "${ARCHIVE_NAME}.zip.asc" --armor --detach-sign "${ARCHIVE_NAME}.zip"
          gpg --batch --yes --output "${ARCHIVE_NAME}.tar.gz.asc" --armor --detach-sign "${ARCHIVE_NAME}.tar.gz"
          echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> "${GITHUB_OUTPUT}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          body: |
            See [CHANGELOG](https://github.com/elastisys/compliantkubernetes-kubespray/blob/${{ github.ref_name }}/changelog/${{ steps.get_series.outputs.SERIES }}.md) for details.
          files: |
            public.signing.key
            ${{ steps.create_archive.outputs.ARCHIVE_NAME }}.zip
            ${{ steps.create_archive.outputs.ARCHIVE_NAME }}.zip.asc
            ${{ steps.create_archive.outputs.ARCHIVE_NAME }}.tar.gz
            ${{ steps.create_archive.outputs.ARCHIVE_NAME }}.tar.gz.asc
